name: Build Status

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # run on sunday nights
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
        event-name: [push]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cmake -Bbuild -H.
        cmake --build build/ --target all

    # - name: Lint
    #   run: |
    #     make lint

    # - name: Test
    #   run: |
    #     make tests
    #   if: ${{ github.event_name == matrix.event-name || matrix.os == 'ubuntu-latest' }}

